from app.router import KeywordRouter


def test_keyword_routing():
    router = KeywordRouter()
    assert router.classify("search python logging best practices") == "research"
    assert router.classify("read file C:\\temp\\x.txt") == "code"
    assert router.classify("take screenshot now") == "desktop"
    assert router.classify("save note remember this") == "memory"
    assert router.classify("hello there") == "chat"
    assert router.classify("who is the current president as of 05/08/2026") == "research"
    assert router.classify("no who is the vice president of america?") == "research"
    assert (
        router.classify(
            "search for dolphins on my pc on google and look at the images and download that image"
        )
        == "desktop"
    )
    assert router.classify("visualize desktop") == "desktop"
    assert router.classify("visualize desktop understanding") == "desktop"
    assert router.classify("show me what you see") == "desktop"
    assert router.classify('write "workspace/final_pass/test_note.txt" "hello"') == "code"
    assert router.classify('read "workspace/final_pass/test_note.txt"') == "code"
    assert router.classify("make me a new website locally on my pc") == "code"
    assert router.classify("build me a website") == "code"
    assert router.classify("make a basic local website") == "code"
    assert router.classify("create a simple website") == "code"
    assert router.classify("make me a website with html css and javascript") == "code"
    assert router.classify("make a local website in a new folder") == "code"
    assert router.classify("make me a product landing page for LocalPilot") == "code"
    assert router.classify("make me a dark futuristic website for an AI assistant") == "code"
    assert router.classify("search the website for prices") != "code"
    assert router.classify("open this website") != "code"
    assert router.classify("look up websites about local ai") != "code"
    assert router.classify("make me a notepad app with a gui and double click starter") == "code"
    assert router.classify("verify the generated notepad app files and tell me how to run it") == "code"
    assert router.classify("inspect desktop") == "desktop"
    assert router.classify("what window am I on") == "desktop"
    assert router.classify("what is under my mouse") == "desktop"
    assert router.classify("page inspect") == "desktop"
    assert router.classify("page confidence") == "desktop"
    assert router.classify("show page understanding") == "desktop"
    assert router.classify("show desktop lessons") == "desktop"
    assert router.classify("ocr screenshot") == "desktop"
    assert router.classify("read screen text") == "desktop"
    assert router.classify("page ocr") == "desktop"
    assert router.classify("gui settings are confusing") == "chat"
    assert router.classify("notepad is a useful app") != "memory"
    assert router.classify("professional build make me a notepad app with a gui and double click starter") == "code"
    assert router.classify("run pytest") == "code"
    assert router.classify("verify LocalPilot") == "code"
